---
# tasks file for create_mediatype
- name: 'Create a script mediatype'
  zabbix_mediatype:
    name: "my script"
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_username }}"
    login_password: "{{ zabbix_password }}"
    type: 'script'
    script_name: 'my_script.py'
    script_params:
      - 'arg1'
      - 'arg2'
