---
# create group
- name: Create host groups
  local_action:
    module: zabbix_group
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_username }}"
    login_password: "{{ zabbix_password }}"
    state: present
    host_groups:
      - "{{ group_1 }}"
      - "{{ group_2 }}"
