---
# tasks file for create_proxy
- name: Create a new proxy or update an existing proxy
  local_action:
    module: zabbix_proxy
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_username }}"
    login_password: "{{ zabbix_password }}"
    proxy_name: ExampleProxy
    description: ExampleProxy
    status: active
    state: present
    interface:
        type: 1 
        main: 1
        useip: 1
        ip: 192.168.128.51
        dns: ""
        port: 10050
